In [83]:
from numpy import*
from pandas import *
from matplotlib.pyplot import*
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [84]:
df=read_csv('Advertising.csv')
df = df.iloc[:, 1:]

In [85]:
df.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [86]:
X=df.drop('Sales',axis=1)

In [87]:
X

TV  Radio  Newspaper
0    230.1   37.8       69.2
1     44.5   39.3       45.1
2     17.2   45.9       69.3
3    151.5   41.3       58.5
4    180.8   10.8       58.4
..     ...    ...        ...
195   38.2    3.7       13.8
196   94.2    4.9        8.1
197  177.0    9.3        6.4
198  283.6   42.0       66.2
199  232.1    8.6        8.7

[200 rows x 3 columns]

In [88]:
Y=df['Sales'].values

In [89]:
r=LinearRegression()
r.fit(X,Y)


LinearRegression()

In [90]:
r.score(X,Y)

0.8972106381789522

In [91]:
pred =r.predict([[150,41,60]])


c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [92]:
pred

array([17.4710673])

In [93]:
pred2=r.predict([[24.5,35,68]])

c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [94]:
pred2

array([10.58812425])

In [95]:
from sklearn.preprocessing import PolynomialFeatures
r2=PolynomialFeatures(degree=8)
X2=r2.fit_transform(X)

In [96]:
lin_reg_2 = LinearRegression()
lin_reg_2.fit(X2, Y)

LinearRegression()

In [97]:
lin_reg_2.score(X2,Y)

0.9934636200726805

In [98]:
pred =lin_reg_2.predict(r2.fit_transform([[24.5,35,68]]))

In [99]:
pred

array([8.75161356])